spring.application.name=petescars

spring.datasource.url=jdbc:mysql://sql5.freesqldatabase.com:3306/sql5774324
spring.datasource.username=sql5774324
spring.datasource.password=B9b4JH2Bml
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# HikariCP Pool Settings - Tweak for shared/free MySQL hosting
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000
